import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
    version: 1,
    tables: [
        tableSchema({
            name: 'users',
            columns: [
                { name: 'protagonist_name', type: 'string' },
                { name: 'birth_year', type: 'number' },
                { name: 'birth_month', type: 'number' },
                { name: 'birth_day', type: 'number' },
                { name: 'public_key', type: 'string' },
                { name: 'story_tone_preference', type: 'string' },
                { name: 'is_premium', type: 'boolean' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'entries',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'date', type: 'number', isIndexed: true },
                { name: 'year', type: 'number', isIndexed: true },
                { name: 'month', type: 'number' },
                { name: 'day', type: 'number' },
                { name: 'entry_type', type: 'string' },
                { name: 'encrypted_content', type: 'string' },
                { name: 'content_nonce', type: 'string' },
                { name: 'mood', type: 'string', isOptional: true },
                { name: 'goal_achieved', type: 'boolean', isOptional: true },
                { name: 'goal_reviewed_at', type: 'number', isOptional: true },
                { name: 'encrypted_photo_refs', type: 'string', isOptional: true },
                { name: 'share_activity_to_circles', type: 'boolean' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'stories',
            columns: [
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'encrypted_title', type: 'string' },
                { name: 'encrypted_content', type: 'string' },
                { name: 'content_nonce', type: 'string' },
                { name: 'scope', type: 'string' },
                { name: 'scope_detail', type: 'string', isOptional: true },
                { name: 'generated_at', type: 'number' },
                { name: 'word_count', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'circles',
            columns: [
                { name: 'owner_id', type: 'string', isIndexed: true },
                { name: 'name', type: 'string' },
                { name: 'encrypted_group_key', type: 'string' },
                { name: 'member_count', type: 'number' },
                { name: 'created_at', type: 'number' },
                { name: 'updated_at', type: 'number' },
            ],
        }),
        tableSchema({
            name: 'circle_members',
            columns: [
                { name: 'circle_id', type: 'string', isIndexed: true },
                { name: 'user_id', type: 'string', isIndexed: true },
                { name: 'display_name', type: 'string' },
                { name: 'public_key', type: 'string' },
                { name: 'encrypted_group_key_for_member', type: 'string' },
                { name: 'role', type: 'string' },
                { name: 'joined_at', type: 'number' },
                { name: 'share_entry_count', type: 'boolean' },
                { name: 'share_mood_summary', type: 'boolean' },
                { name: 'share_goal_progress', type: 'boolean' },
                { name: 'share_streaks', type: 'boolean' },
            ],
        }),
        tableSchema({
            name: 'feed_items',
            columns: [
                { name: 'circle_id', type: 'string', isIndexed: true },
                { name: 'author_id', type: 'string', isIndexed: true },
                { name: 'author_display_name', type: 'string' },
                { name: 'type', type: 'string' },
                { name: 'encrypted_payload', type: 'string' },
                { name: 'payload_nonce', type: 'string' },
                { name: 'created_at', type: 'number', isIndexed: true },
                { name: 'expires_at', type: 'number', isOptional: true },
            ],
        }),
    ],
});
